<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $hotels = [
            [
                'name' => 'Hôtel Le Consul',
                'etoile' => 4,
                'ville_id' => 1,
                'supplier_id' => 1,
                'adresse' => '123 Main Street, Tunis',
                'description' => 'Un hôtel luxueux avec des équipements haut de gamme.',
                'latitude' => '36.8188',
                'longitude' => '10.1658',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 200.00,
                'images'=>'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/0f/55/f0/hotel-le-consul.jpg?w=700&h=-1&s=1',
            ],
            [
                'name' => 'Hôtel Tunisie Palace',
                'etoile' => 5,
                'ville_id' => 1,
                'supplier_id' => 2,
                'adresse' => '456 Oak Street, Tunis',
                'description' => 'Un hôtel cinq étoiles offrant une expérience de luxe ultime.',
                'latitude' => '36.8000',
                'longitude' => '10.1838',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 300.00,
                'images'=>'https://pix10.agoda.net/hotelImages/168824/-1/d06a1b00730ec0b661ecbd890070a1d0.jpg',
            ],
            [
                'name' => 'Hôtel Tunis Riviera',
                'etoile' => 3,
                'ville_id' => 1,
                'supplier_id' => 1,
                'adresse' => '789 Maple Avenue, Tunis',
                'description' => 'Un hôtel avec une vue magnifique sur la mer.',
                'latitude' => '36.8124',
                'longitude' => '10.1843',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => false,
                'prix_chambre' => 150.00,
                'images'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL3MVUYNzaLhJXx32lyKbr7t_WYxtL3lWdRQ&usqp=CAU',
            ],
            [
                'name' => 'Hôtel Tunisien',
                'etoile' => 4,
                'ville_id' => 3,
                'supplier_id' => 2,
                'adresse' => '101 Pine Street, Sousse',
                'description' => 'Un hôtel moderne avec une ambiance méditerranéenne.',
                'latitude' => '35.8252',
                'longitude' => '10.6350',
                'status' => true,
                'vue_mere' => false,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 220.00,
                'images'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-2fwFXK8ukZIJjVwWxjJjl-yqDbh7PQU-mA&usqp=CAU',
            ],
            [
                'name' => 'Hôtel Médina Beach',
                'etoile' => 4,
                'ville_id' => 6,
                'supplier_id' => 2,
                'adresse' => '210 Cedar Avenue, Hammamet',
                'description' => 'Un hôtel près de la plage avec une atmosphère apaisante.',
                'latitude' => '36.4057',
                'longitude' => '10.6178',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 180.00,
                'images'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtRQ8_VLq_QHXlbXIn6im16_MPkz2lEh4vDA&usqp=CAU',
            ],
            [
                'name' => 'Hôtel Oasis Palace',
                'etoile' => 3,
                'ville_id' => 20,
                'supplier_id' => 2,
                'adresse' => '315 Elm Street, Tozeur',
                'description' => 'Un hôtel avec des jardins luxuriants et une ambiance chaleureuse.',
                'latitude' => '33.9188',
                'longitude' => '8.1304',
                'status' => true,
                'vue_mere' => false,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 120.00,
                'images'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8FZNiIi88jNNlsbPEm7acSbrN6mXxBFHZMQ&usqp=CAU',
            ],
            [
                'name' => 'Hôtel Sahara Resort',
                'etoile' => 5,
                'ville_id' => 20,
                'supplier_id' => 1,
                'adresse' => '501 Birch Street, Douz',
                'description' => 'Un complexe cinq étoiles au cœur du désert.',
                'latitude' => '33.4618',
                'longitude' => '9.0273',
                'status' => true,
                'vue_mere' => false,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 350.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Golden Sands',
                'etoile' => 4,
                'ville_id' => 11,
                'supplier_id' => 2,
                'adresse' => '123 Pine Street, Monastir',
                'description' => 'Un hôtel avec une plage privée et une cuisine raffinée.',
                'latitude' => '35.7744',
                'longitude' => '10.8240',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 280.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Carthage Bay',
                'etoile' => 3,
                'ville_id' => 1,
                'supplier_id' => 1,
                'adresse' => '789 Cedar Avenue, Carthage',
                'description' => 'Un hôtel tranquille avec une vue sur la baie de Carthage.',
                'latitude' => '36.8531',
                'longitude' => '10.3255',
                'status' => true,
                'vue_mere' => true,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 160.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Jasmine Palace',
                'etoile' => 4,
                'ville_id' => 6,
                'supplier_id' => 2,
                'adresse' => '210 Oak Street, Nabeul',
                'description' => 'Un palais luxueux avec des jardins enchanteurs.',
                'latitude' => '36.4578',
                'longitude' => '10.7395',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 250.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Azure Beach',
                'etoile' => 5,
                'ville_id' => 2,
                'supplier_id' => 1,
                'adresse' => '500 Palm Street, Sfax',
                'description' => 'Un hôtel de luxe en bord de mer avec une vue imprenable.',
                'latitude' => '34.7465',
                'longitude' => '10.7591',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 400.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Crystal Springs',
                'etoile' => 4,
                'ville_id' => 4,
                'supplier_id' => 2,
                'adresse' => '300 Cedar Avenue, Bizerte',
                'description' => 'Un lieu de détente avec des sources cristallines.',
                'latitude' => '37.2732',
                'longitude' => '9.8673',
                'status' => true,
                'vue_mere' => false,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 180.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Royal Gardens',
                'etoile' => 5,
                'ville_id' => 6,
                'supplier_id' => 1,
                'adresse' => '700 Rose Street, Nabeul',
                'description' => 'Un jardin royal avec un hébergement de classe mondiale.',
                'latitude' => '36.4604',
                'longitude' => '10.7389',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 350.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Majestic View',
                'etoile' => 4,
                'ville_id' => 2,
                'supplier_id' => 2,
                'adresse' => '800 Lily Street, Sfax',
                'description' => 'Une vue majestueuse et un séjour inoubliable.',
                'latitude' => '34.7506',
                'longitude' => '10.7567',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 280.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Coral Retreat',
                'etoile' => 3,
                'ville_id' => 1,
                'supplier_id' => 1,
                'adresse' => '900 Ocean Street, Tunis',
                'description' => 'Une retraite corallienne avec un ambiance détendue.',
                'latitude' => '36.7988',
                'longitude' => '10.1756',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => false,
                'prix_chambre' => 150.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Mirage Oasis',
                'etoile' => 5,
                'ville_id' => 11,
                'supplier_id' => 2,
                'adresse' => '1001 Palm Street, Monastir',
                'description' => 'Une oasis de luxe avec des installations de classe mondiale.',
                'latitude' => '35.7735',
                'longitude' => '10.8261',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 400.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Harmony Gardens',
                'etoile' => 4,
                'ville_id' => 6,
                'supplier_id' => 1,
                'adresse' => '1100 Pine Street, Hammamet',
                'description' => 'Des jardins harmonieux avec un hébergement élégant.',
                'latitude' => '36.4086',
                'longitude' => '10.6178',
                'status' => true,
                'vue_mere' => false,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 220.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Sunflower Paradise',
                'etoile' => 3,
                'ville_id' => 5,
                'supplier_id' => 2,
                'adresse' => '1200 Birch Street, Gabes',
                'description' => 'Un paradis ensoleillé avec des chambres confortables.',
                'latitude' => '33.8910',
                'longitude' => '10.0995',
                'status' => true,
                'vue_mere' => false,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 170.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Ocean Breeze',
                'etoile' => 4,
                'ville_id' => 1,
                'supplier_id' => 1,
                'adresse' => '1300 Cedar Street, Tunis',
                'description' => 'Une brise océanique rafraîchissante avec des installations modernes.',
                'latitude' => '36.8195',
                'longitude' => '10.1656',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 250.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Serenity Cove',
                'etoile' => 3,
                'ville_id' => 11,
                'supplier_id' => 2,
                'adresse' => '1400 Birch Street, Monastir',
                'description' => 'Un havre de sérénité avec des jardins paisibles.',
                'latitude' => '35.7741',
                'longitude' => '10.8243',
                'status' => true,
                'vue_mere' => true,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 180.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Majestic Bay',
                'etoile' => 5,
                'ville_id' => 6,
                'supplier_id' => 1,
                'adresse' => '1500 Palm Street, Hammamet',
                'description' => 'Une baie majestueuse avec un hébergement de luxe.',
                'latitude' => '36.4086',
                'longitude' => '10.6178',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 400.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Tranquil Retreat',
                'etoile' => 4,
                'ville_id' => 2,
                'supplier_id' => 2,
                'adresse' => '1600 Cedar Avenue, Sfax',
                'description' => 'Un refuge tranquille avec des vues apaisantes.',
                'latitude' => '34.7465',
                'longitude' => '10.7567',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 280.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Paradise Cove',
                'etoile' => 3,
                'ville_id' => 1,
                'supplier_id' => 1,
                'adresse' => '1700 Lily Street, Tunis',
                'description' => 'Un coin de paradis avec des jardins luxuriants.',
                'latitude' => '36.7988',
                'longitude' => '10.1756',
                'status' => true,
                'vue_mere' => false,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 150.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Lush Gardens',
                'etoile' => 5,
                'ville_id' => 6,
                'supplier_id' => 1,
                'adresse' => '1900 Cedar Street, Hammamet',
                'description' => 'Des jardins luxuriants avec un service de classe mondiale.',
                'latitude' => '36.4086',
                'longitude' => '10.6178',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 400.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Whispering Pines',
                'etoile' => 4,
                'ville_id' => 5,
                'supplier_id' => 2,
                'adresse' => '2000 Pine Street, Gabes',
                'description' => 'Des pins chuchotants et une ambiance apaisante.',
                'latitude' => '33.8910',
                'longitude' => '10.0995',
                'status' => true,
                'vue_mere' => false,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 280.00,
                'images'=>null
            ],

            [
                'name' => 'Hôtel Tranquility Cove',
                'etoile' => 3,
                'ville_id' => 1,
                'supplier_id' => 1,
                'adresse' => '2100 Rose Street, Tunis',
                'description' => 'Une crique tranquille avec des vues pittoresques.',
                'latitude' => '36.7988',
                'longitude' => '10.1756',
                'status' => true,
                'vue_mere' => true,
                'plage' => false,
                'piscine' => true,
                'prix_chambre' => 200.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Enchanted Oasis',
                'etoile' => 4,
                'ville_id' => 11,
                'supplier_id' => 2,
                'adresse' => '2200 Oak Street, Monastir',
                'description' => 'Une oasis enchantée avec des logements de rêve.',
                'latitude' => '35.7744',
                'longitude' => '10.8240',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 300.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Paradise Cove',
                'etoile' => 5,
                'ville_id' => 6,
                'supplier_id' => 1,
                'adresse' => '2300 Cedar Street, Hammamet',
                'description' => 'Une crique paradisiaque avec des équipements de luxe.',
                'latitude' => '36.4086',
                'longitude' => '10.6178',
                'status' => true,
                'vue_mere' => true,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 450.00,
                'images'=>null
            ],
            [
                'name' => 'Hôtel Sunset Serenity',
                'etoile' => 4,
                'ville_id' => 5,
                'supplier_id' => 2,
                'adresse' => '2400 Pine Street, Gabes',
                'description' => 'Une sérénité au coucher du soleil avec des vues spectaculaires.',
                'latitude' => '33.8910',
                'longitude' => '10.0995',
                'status' => true,
                'vue_mere' => false,
                'plage' => true,
                'piscine' => true,
                'prix_chambre' => 320.00,
                'images'=>null
            ],


        ];

        DB::table('hotels')->insert($hotels);
    }
}
